# Generated by Django 5.1.3 on 2024-12-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0004_formfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
