# Generated by Django 5.1.3 on 2024-12-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0005_delete_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
